// <auto-generated />
using System;
using CardiTrack.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CardiTrack.Infrastructure.Migrations
{
    [DbContext(typeof(CardiTrackDbContext))]
    [Migration("20260312180945_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CardiTrack.Domain.Entities.ActivityLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("ActiveMinutes")
                        .HasColumnType("integer");

                    b.Property<int?>("AvgHeartRate")
                        .HasColumnType("integer");

                    b.Property<int?>("AwakeMinutes")
                        .HasColumnType("integer");

                    b.Property<decimal?>("BreathingRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("CaloriesBurned")
                        .HasColumnType("integer");

                    b.Property<Guid>("CardiMemberId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("DataSource")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int?>("DeepSleepMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid>("DeviceConnectionId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Distance")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("Floors")
                        .HasColumnType("integer");

                    b.Property<int?>("LightSleepMinutes")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxHeartRate")
                        .HasColumnType("integer");

                    b.Property<int?>("MinHeartRate")
                        .HasColumnType("integer");

                    b.Property<int?>("RemSleepMinutes")
                        .HasColumnType("integer");

                    b.Property<int?>("RestingHeartRate")
                        .HasColumnType("integer");

                    b.Property<int?>("SedentaryMinutes")
                        .HasColumnType("integer");

                    b.Property<int?>("SleepEfficiency")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SleepEndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("SleepMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SleepStartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("SpO2Average")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("SpO2Max")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("SpO2Min")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("Steps")
                        .HasColumnType("integer");

                    b.Property<int?>("StressScore")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Temperature")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("VO2Max")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("CardiMemberId");

                    b.HasIndex("DataSource");

                    b.HasIndex("Date");

                    b.HasIndex("DeviceConnectionId");

                    b.HasIndex("CardiMemberId", "Date")
                        .IsUnique();

                    b.ToTable("ActivityLogs", (string)null);
                });

            modelBuilder.Entity("CardiTrack.Domain.Entities.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AcknowledgedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AcknowledgedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("CardiMemberId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsResolved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("MetricValues")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("TriggeredDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AlertType");

                    b.HasIndex("CardiMemberId");

                    b.HasIndex("IsResolved");

                    b.HasIndex("Severity");

                    b.HasIndex("TriggeredDate");

                    b.HasIndex("CardiMemberId", "IsResolved", "TriggeredDate");

                    b.ToTable("Alerts", (string)null);
                });

            modelBuilder.Entity("CardiTrack.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("CardiMemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("ChangedFields")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("DataAccessed")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RequestPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("ResponseStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CardiMemberId");

                    b.HasIndex("EntityType");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId");

                    b.HasIndex("CardiMemberId", "Timestamp");

                    b.HasIndex("UserId", "Timestamp");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("CardiTrack.Domain.Entities.CardiMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("EmergencyContactName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EmergencyContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastSyncDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MedicalNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("LastSyncDate");

                    b.HasIndex("OrganizationId");

                    b.ToTable("CardiMembers", (string)null);
                });

            modelBuilder.Entity("CardiTrack.Domain.Entities.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiEndpoint")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Capabilities")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasDefaultValue("{}");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OAuthConfig")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DeviceType");

                    b.HasIndex("IsActive");

                    b.HasIndex("SortOrder");

                    b.ToTable("Devices", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0000-0000-000000000001"),
                            ApiEndpoint = "https://api.fitbit.com",
                            Capabilities = "{\"hasHeartRate\":true,\"hasSleep\":true,\"hasActivity\":true,\"hasSpO2\":true,\"hasStress\":false}",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeviceType = "Fitbit",
                            DisplayName = "Fitbit",
                            IsActive = true,
                            Manufacturer = "Fitbit / Google",
                            ModelName = "All Models",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0002-0000-0000-000000000002"),
                            Capabilities = "{\"hasHeartRate\":true,\"hasSleep\":true,\"hasActivity\":true,\"hasSpO2\":true,\"hasECG\":true}",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeviceType = "AppleWatch",
                            DisplayName = "Apple Watch",
                            IsActive = false,
                            Manufacturer = "Apple",
                            ModelName = "All Models",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0003-0000-0000-000000000003"),
                            ApiEndpoint = "https://healthapi.garmin.com",
                            Capabilities = "{\"hasHeartRate\":true,\"hasSleep\":true,\"hasActivity\":true,\"hasSpO2\":true,\"hasStress\":true}",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeviceType = "Garmin",
                            DisplayName = "Garmin",
                            IsActive = false,
                            Manufacturer = "Garmin",
                            ModelName = "All Models",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0004-0000-0000-000000000004"),
                            ApiEndpoint = "https://api.shealth.samsung.com",
                            Capabilities = "{\"hasHeartRate\":true,\"hasSleep\":true,\"hasActivity\":true,\"hasSpO2\":true}",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeviceType = "Samsung",
                            DisplayName = "Samsung Galaxy Watch",
                            IsActive = false,
                            Manufacturer = "Samsung",
                            ModelName = "Galaxy Watch",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0005-0000-0000-000000000005"),
                            ApiEndpoint = "https://wbsapi.withings.net",
                            Capabilities = "{\"hasHeartRate\":true,\"hasSleep\":true,\"hasActivity\":true,\"hasSpO2\":true,\"hasTemperature\":true}",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeviceType = "Withings",
                            DisplayName = "Withings",
                            IsActive = false,
                            Manufacturer = "Withings",
                            ModelName = "All Models",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0006-0000-0000-000000000006"),
                            ApiEndpoint = "https://api.ouraring.com",
                            Capabilities = "{\"hasHeartRate\":true,\"hasSleep\":true,\"hasActivity\":true,\"hasSpO2\":true,\"hasTemperature\":true,\"hasHRV\":true}",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeviceType = "Oura",
                            DisplayName = "Oura Ring",
                            IsActive = false,
                            Manufacturer = "Oura",
                            ModelName = "Oura Ring",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0007-0000-0000-000000000007"),
                            ApiEndpoint = "https://api.prod.whoop.com",
                            Capabilities = "{\"hasHeartRate\":true,\"hasSleep\":true,\"hasActivity\":true,\"hasHRV\":true,\"hasStress\":true}",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeviceType = "Whoop",
                            DisplayName = "WHOOP",
                            IsActive = false,
                            Manufacturer = "WHOOP",
                            ModelName = "WHOOP Strap",
                            SortOrder = 7
                        });
                });

            modelBuilder.Entity("CardiTrack.Domain.Entities.DeviceConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessToken")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("CardiMemberId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ConnectedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConnectionStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastSyncDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Metadata")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Scopes")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasDefaultValue("[]");

                    b.Property<int>("SyncFrequencyMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(30);

                    b.Property<DateTime?>("TokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CardiMemberId");

                    b.HasIndex("ConnectionStatus");

                    b.HasIndex("DeviceType");

                    b.HasIndex("LastSyncDate");

                    b.HasIndex("CardiMemberId", "IsPrimary");

                    b.ToTable("DeviceConnections", (string)null);
                });

            modelBuilder.Entity("CardiTrack.Domain.Entities.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Type");

                    b.ToTable("Organizations", (string)null);
                });

            modelBuilder.Entity("CardiTrack.Domain.Entities.PatternBaseline", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AvgActiveMinutes")
                        .HasColumnType("integer");

                    b.Property<int?>("AvgRestingHeartRate")
                        .HasColumnType("integer");

                    b.Property<int?>("AvgSleepEfficiency")
                        .HasColumnType("integer");

                    b.Property<int?>("AvgSleepMinutes")
                        .HasColumnType("integer");

                    b.Property<int?>("AvgSteps")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CalculatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("CardiMemberId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("MaxHeartRateObserved")
                        .HasColumnType("integer");

                    b.Property<int>("PeriodDays")
                        .HasColumnType("integer");

                    b.Property<decimal?>("StdDevHeartRate")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("StdDevSteps")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("StepsByDayOfWeek")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<TimeOnly?>("TypicalBedtime")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly?>("TypicalWakeTime")
                        .HasColumnType("time without time zone");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CalculatedDate");

                    b.HasIndex("CardiMemberId");

                    b.HasIndex("CardiMemberId", "PeriodDays", "CalculatedDate");

                    b.ToTable("PatternBaselines", (string)null);
                });

            modelBuilder.Entity("CardiTrack.Domain.Entities.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BillingCycle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("USD");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Features")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasDefaultValue("{}");

                    b.Property<int>("MaxCardiMembers")
                        .HasColumnType("integer");

                    b.Property<int>("MaxUsers")
                        .HasColumnType("integer");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("StartDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("TrialEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("Status", "EndDate");

                    b.ToTable("Subscriptions", (string)null);
                });

            modelBuilder.Entity("CardiTrack.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Auth0UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("CardiTrack.Domain.Entities.UserCardiMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("CanViewHealthData")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid>("CardiMemberId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsPrimaryCaregiver")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("NotificationPreferences")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasDefaultValue("{}");

                    b.Property<bool>("ReceiveAlerts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("RelationshipType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CardiMemberId");

                    b.HasIndex("IsPrimaryCaregiver");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "CardiMemberId", "IsActive");

                    b.ToTable("UserCardiMembers", (string)null);
                });

            modelBuilder.Entity("CardiTrack.Domain.Entities.UserCardiMember", b =>
                {
                    b.HasOne("CardiTrack.Domain.Entities.CardiMember", "CardiMember")
                        .WithMany()
                        .HasForeignKey("CardiMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CardiTrack.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CardiMember");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
